### ISSUE TITLE
Update to JokeAPI 2.0

### ISSUE THREAD

**Issue by airs747** [Kreshnik/MMM-JokeAPI#2]
The JokeAPI used in this module is going to be deprecated by June 2020, see https://sv443.net/jokeapi
The fix is simple, I think, update the URL used to v2.0

**Comment by xvolte** [comment]
Thanks, i was able to fix it on my side by replacing the url per this :
https://sv443.net/jokeapi/v2/joke/${this.config.category}

**Comment by Kreshnik** [comment]
Thank you @airs747 and @xvolte the API has been updated to `v2` 7a7715e5f2fb04bf38d418100b1e33755e4048c5
